import request from '@/utils/request'

export const getWorkstationPage = (data) => request.post('/workstation/page', data)
export const getWorkstationList = () => request.get('/workstation/list')
export const getWorkstation = (id) => request.get(`/workstation/${id}`)
export const saveWorkstation = (data) => request.post('/workstation', data)
export const updateWorkstation = (data) => request.put('/workstation', data)
export const deleteWorkstation = (id) => request.delete(`/workstation/${id}`)

export const getSchedulePage = (data) => request.post('/schedule/page', data)
export const getSchedule = (id) => request.get(`/schedule/${id}`)
export const createSchedule = (data, teamLeaderId) => request.post(`/schedule?teamLeaderId=${teamLeaderId}`, data)
export const updateSchedule = (data) => request.put('/schedule', data)
export const deleteSchedule = (id) => request.delete(`/schedule/${id}`)
export const startWork = (id, welderId) => request.post(`/schedule/${id}/start?welderId=${welderId}`)
export const confirmProcessCard = (data) => request.post('/schedule/confirmProcess', data)
export const submitFirstInspection = (id) => request.post(`/schedule/${id}/submitInspection`)
export const completeWork = (id) => request.post(`/schedule/${id}/complete`)
export const suspendWork = (id, reason) => request.post(`/schedule/${id}/suspend?reason=${encodeURIComponent(reason)}`)
export const resumeWork = (id) => request.post(`/schedule/${id}/resume`)
export const cancelSchedule = (id) => request.post(`/schedule/${id}/cancel`)
export const getSafetyChecks = (id) => request.get(`/schedule/${id}/safetyChecks`)
export const saveSafetyChecks = (data) => request.post('/schedule/safetyChecks', data)
export const getStartPermitStatus = (id) => request.get(`/schedule/${id}/permitStatus`)
export const getScheduleDetail = (id) => request.get(`/schedule/${id}/detail`)

export const getHotWorkPermitList = () => request.get('/hotwork/list')
export const getHotWorkPermit = (id) => request.get(`/hotwork/${id}`)
export const getHotWorkPermitByWorkstation = (workstationId) => request.get(`/hotwork/workstation/${workstationId}`)
export const saveHotWorkPermit = (data, applicantId) => request.post(`/hotwork?applicantId=${applicantId}`, data)
export const approveHotWorkPermit = (id, approverId) => request.post(`/hotwork/${id}/approve?approverId=${approverId}`)
export const rejectHotWorkPermit = (id, approverId) => request.post(`/hotwork/${id}/reject?approverId=${approverId}`)

export const getDeviationList = () => request.get('/deviation/list')
export const getDeviation = (id) => request.get(`/deviation/${id}`)
export const getDeviationByProcessCard = (processCardId) => request.get(`/deviation/processCard/${processCardId}`)
export const saveDeviation = (data, applicantId) => request.post(`/deviation?applicantId=${applicantId}`, data)
export const approveDeviation = (id, reviewerId) => request.post(`/deviation/${id}/approve?reviewerId=${reviewerId}`)
export const rejectDeviation = (id, reviewerId, opinion) => request.post(`/deviation/${id}/reject?reviewerId=${reviewerId}&opinion=${encodeURIComponent(opinion)}`)

export const getSafetyReviewPending = () => request.get('/safetyReview/pending')
export const getSafetyReviewList = () => request.get('/safetyReview/list')
export const getSafetyReview = (id) => request.get(`/safetyReview/${id}`)
export const getSafetyReviewBySchedule = (scheduleId) => request.get(`/safetyReview/schedule/${scheduleId}`)
export const approveSafetyReview = (id, reviewerId, safetyMeasures, reviewOpinion) => request.post(`/safetyReview/${id}/approve?reviewerId=${reviewerId}&safetyMeasures=${encodeURIComponent(safetyMeasures || '')}&reviewOpinion=${encodeURIComponent(reviewOpinion || '')}`)
export const rejectSafetyReview = (id, reviewerId, reviewOpinion) => request.post(`/safetyReview/${id}/reject?reviewerId=${reviewerId}&reviewOpinion=${encodeURIComponent(reviewOpinion)}`)

export const getWeldSeamReportList = () => request.get('/weldSeamReport/list')
export const getWeldSeamReport = (id) => request.get(`/weldSeamReport/${id}`)
export const getWeldSeamReportBySeamNo = (weldSeamNo) => request.get(`/weldSeamReport/seam/${weldSeamNo}`)
export const getWeldSeamReportBySchedule = (scheduleId) => request.get(`/weldSeamReport/schedule/${scheduleId}`)
export const saveWeldSeamReport = (data) => request.post('/weldSeamReport', data)
export const checkWeldSeamLocked = (weldSeamNo) => request.get(`/weldSeamReport/locked/${weldSeamNo}`)
