import request from '@/utils/request'

export const getWorkstationPage = (data) => request.post('/workstation/page', data)
export const getWorkstationList = () => request.get('/workstation/list')
export const getWorkstation = (id) => request.get(`/workstation/${id}`)
export const saveWorkstation = (data) => request.post('/workstation', data)
export const updateWorkstation = (data) => request.put('/workstation', data)
export const deleteWorkstation = (id) => request.delete(`/workstation/${id}`)

export const getSchedulePage = (data) => request.post('/schedule/page', data)
export const getSchedule = (id) => request.get(`/schedule/${id}`)
export const createSchedule = (data, teamLeaderId) => request.post(`/schedule?teamLeaderId=${teamLeaderId}`, data)
export const updateSchedule = (data) => request.put('/schedule', data)
export const deleteSchedule = (id) => request.delete(`/schedule/${id}`)
export const startWork = (id, welderId) => request.post(`/schedule/${id}/start?welderId=${welderId}`)
export const confirmProcessCard = (data) => request.post('/schedule/confirmProcess', data)
export const submitFirstInspection = (id) => request.post(`/schedule/${id}/submitInspection`)
export const completeWork = (id) => request.post(`/schedule/${id}/complete`)
export const suspendWork = (id, reason) => request.post(`/schedule/${id}/suspend?reason=${encodeURIComponent(reason)}`)
export const resumeWork = (id) => request.post(`/schedule/${id}/resume`)
export const cancelSchedule = (id) => request.post(`/schedule/${id}/cancel`)
export const getSafetyChecks = (id) => request.get(`/schedule/${id}/safetyChecks`)
export const saveSafetyChecks = (data) => request.post('/schedule/safetyChecks', data)
export const getStartPermitStatus = (id) => request.get(`/schedule/${id}/permitStatus`)
